-- use vim.keymap.set beyond vim.api.nvim_set_keymap
local opts = { noremap = true, silent = true }
vim.keymap.set("n", "<Leader>o", "o<ESC>", opts)
vim.keymap.set("n", "<Leader>O", "O<ESC>", opts)
vim.keymap.set("n", "<leader>w", ":w<CR>", opts)
vim.keymap.set("n", "<leader>wa", ":wa<CR>", opts)
vim.keymap.set("n", "<leader>wq", ":wq<CR>", opts)
vim.keymap.set("n", "<leader>wqa", ":wqa<CR>", opts)
vim.keymap.set("n", "<leader>q", ":q<CR>", opts)
vim.keymap.set("n", "<leader>qq", ":q!<CR>", opts)
vim.keymap.set("n", "<leader>qa", ":qa<CR>", opts)
vim.keymap.set("n", "<leader>qaa", ":qa!<CR>", opts)
vim.keymap.set("n", "<leader>a", "ggvG", opts)
vim.keymap.set("n", "j", "gj", opts)
vim.keymap.set("n", "k", "gk", opts)
vim.keymap.set("n", "<Esc><Esc>", ":nohlsearch<CR><Esc>", opts)
vim.keymap.set("n", "Y", "y$", opts)
-- vim buffer
vim.keymap.set("n", "<leader>be", ":enew<CR>", opts)
vim.keymap.set("n", "<leader>bd", ":bd<CR>", opts)
vim.keymap.set("n", "<leader>bdd", ":bd!<CR>", opts)
vim.keymap.set("n", "<leader>bp", ":bprevious<CR>", opts)
vim.keymap.set("n", "<leader>bn", ":bnext<CR>", opts)
vim.keymap.set("n", "<leader>Bf", ":bfirst<CR>", opts)
vim.keymap.set("n", "<leader>Bl", ":blast<CR>-vim", opts)
-- vim tab
vim.keymap.set("n", "tf", ":<C-u>tabfirst<CR>", opts)
vim.keymap.set("n", "tl", ":<C-u>tablast<CR>", opts)
vim.keymap.set("n", "tn", ":<C-u>tabnext<CR>", opts)
vim.keymap.set("n", "tp", ":<C-u>tabprevious<CR>", opts)
vim.keymap.set("n", "te", ":<C-u>tabedit<CR>", opts)
vim.keymap.set("n", "tw", ":<C-u>tabclose<CR>", opts)
vim.keymap.set("n", "to", ":<C-u>tabonly<CR>", opts)
vim.keymap.set("n", "ts", ":<C-u>tabs<CR>", opts)
-- lsp
vim.keymap.set("n", "K", "<cmd>lua vim.lsp.buf.hover()<CR>", opts)
vim.keymap.set("n", "gf", "<cmd>lua vim.lsp.buf.jormatting()<CR>", opts)
vim.keymap.set("n", "gr", "<cmd>lua vim.lsp.buf.references()<CR>", opts)
vim.keymap.set("n", "gd", "<cmd>lua vim.lsp.buf.definition()<CR>", opts)
vim.keymap.set("n", "gD", "<cmd>lua vim.lsp.buf.declaration()<CR>", opts)
vim.keymap.set("n", "gi", "<cmd>lua vim.lsp.buf.implementation()<CR>", opts)
vim.keymap.set("n", "gt", "<cmd>lua vim.lsp.buf.type_definition()<CR>", opts)
vim.keymap.set("n", "gn", "<cmd>lua vim.lsp.buf.rename()<CR>", opts)
vim.keymap.set("n", "ga", "<cmd>lua vim.lsp.buf.code_action()<CR>", opts)
vim.keymap.set("n", "ge", "<cmd>lua vim.diagnostic.open_float()<CR>", opts)
vim.keymap.set("n", "g]", "<cmd>lua vim.diagnostic.goto_next()<CR>", opts)
vim.keymap.set("n", "g[", "<cmd>lua vim.diagnostic.goto_prev()<CR>", opts)
vim.keymap.set("n", "<space>d", vim.diagnostic.open_float, opts)
vim.keymap.set("n", "[d", vim.diagnostic.goto_prev, opts)
vim.keymap.set("n", "]d", vim.diagnostic.goto_next, opts)
-- fzf-lua
vim.keymap.set("n", "<leader>bl", ":FzfLua buffers<CR>", opts)
vim.keymap.set("n", "<leader>lg", ":FzfLua live_grep<CR>", opts)
vim.keymap.set("n", "<C-p>", ":FzfLua files<CR>", opts)
vim.keymap.set("n", "<leader>ch", ":FzfLua command_history<CR>", opts)
vim.keymap.set("n", "<leader>km", ":FzfLua keymaps<CR>", opts)
vim.keymap.set("n", "reg", ":FzfLua registers<CR>", opts)
-- trouble
vim.keymap.set("n", "<leader>xx", "<cmd>TroubleToggle<cr>", opts)
vim.keymap.set("n", "<leader>xw", "<cmd>TroubleToggle workspace_diagnostics<cr>", opts)
vim.keymap.set("n", "<leader>xd", "<cmd>TroubleToggle document_diagnostics<cr>", opts)
vim.keymap.set("n", "<leader>xl", "<cmd>TroubleToggle loclist<cr>", opts)
vim.keymap.set("n", "<leader>xq", "<cmd>TroubleToggle quickfix<cr>", opts)
vim.keymap.set("n", "gR", "<cmd>TroubleToggle lsp_references<cr>", opts)
-- diffview
vim.keymap.set("n", "<leader>gd", ":DiffviewFileHistory %<CR>", opts)
vim.keymap.set("n", "gd", ":DiffviewToggleFiles<CR>", opts)
-- neo-tree
vim.keymap.set("n", "<leader>e", ":NeoTreeFloatToggle<CR>", opts)
-- hop
vim.keymap.set("n", "<leader>k", ":HopLineBC<CR>", opts)
vim.keymap.set("n", "<leader>j", ":HopLineAC<CR>", opts)
